kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
# clusters:
# - cluster:
#     server: ${aws_eks_cluster.cluster.endpoint}
#     certificate-authority-data: ${aws_eks_cluster.cluster.certificate_authority[0].data}
#   name: kubernetes
# contexts:
# - context:
#     cluster: kubernetes
#     user: "${aws_eks_cluster.cluster.name}"
#   name: "${aws_eks_cluster.cluster.name}"
# current-context: "${aws_eks_cluster.cluster.name}"
# kind: Config
# preferences: {}
# users:
# - name: "${aws_eks_cluster.cluster.name}"
#   user:
#     exec:
#       apiVersion: client.authentication.k8s.io/v1
#       command: aws
#       interactiveMode: IfAvailable
#       args:
#         - eks
#         - get-token
#         - --cluster-name
#         - "${aws_eks_cluster.cluster.name}"
# KUBECONFIG
# }
